version: '3.7'
services:
  front:
    image: node:12
    tty: true
    command: bash -c "npm install && npm run serve"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - 8080:8080
    working_dir: /app
    networks:
      - app

volumes:
  node_modules:

networks:
  app:
